version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "NFTGalleryBackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xbwi2rjamp5a"
s3_prefix = "NFTGalleryBackend"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "AlchemyEthUrl=\"https://eth-mainnet.g.alchemy.com/v2/kMJgN17eqdLdIHl1eDI-qlkGyK6eUe4P\" AlchemyEthAPIKey=\"kMJgN17eqdLdIHl1eDI-qlkGyK6eUe4P\" MoralisUrl=\"https://deep-index.moralis.io/api/v2/{address}/nft?normalizeMetadata=true&format=decimal\" MoralisAPIKey=\"jtI2hK1sqK9WpeRN7gPZ1KYsmuP0BrMxeffwu27CGto0arRScuDPWnbBmx2VgZED\" InfuraEthUrl=\"https://mainnet.infura.io/v3/68a634026aa04a1ea7f3d50de4ad3af4\""
